language: erlang
sudo: false
otp_release:
- 17.5
- 18.2
env:
  global:
  - MAIN_OTP=18.2
  matrix:
  - REBAR_VSN=2
  - REBAR_VSN=3
matrix:
  include:
  - env: ELIXIR_VSN=1.2.5 REBAR_VSN=
    otp_release: 18.2

before_install:
- ./scripts/install-prereqs.bash
install:
- ./scripts/install-deps.bash
script:
- ./scripts/run-tests.bash
- ./scripts/run-dialyzer.bash
deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy-hex.bash
  on:
    tags: true
    condition: $REBAR_VSN = '3' && $TRAVIS_OTP_RELEASE = $MAIN_OTP
