language: erlang
sudo: false
otp_release:
- 17.5
- 18.0
- 18.2
env:
  matrix:
  - REBAR_VSN=2
  - REBAR_VSN=3

before_install:
- echo "--> OTP = ${TRAVIS_OTP_RELEASE}"
- ./scripts/install-rebar.sh
install:
- ./scripts/install-deps.sh
script:
- ./scripts/run-tests.sh
- ./scripts/run-dialyzer.sh
deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy-hex.sh
  on:
    tags: true
    condition: $REBAR_VSN = '3' && $TRAVIS_OTP_RELEASE = "18.2"
